### ISSUE TITLE
similar projects

### ISSUE THREAD

**Issue by milahu** [sosuisen/git-documentdb#35]
git backend sounds awesome in terms of portability (free git hosting)

but why reinvent the wheel?
there should be other offline-first libraries
that already have all the wanted features, and just are missing a git backend

https://github.com/topics/offline-first
https://github.com/pazguille/offline-first#tools

related issue https://github.com/pazguille/offline-first/issues/42

**Comment by sosuisen** [comment]
My answer is that Git is what matters.

See also this blog:
https://gitddb.com/blog/powered-by-git-ecosystem
https://gitddb.com/blog/how-to-use-git-as-an-offline-database
https://gitddb.com/blog/pros-and-cons
